"""add vehicles

Revision ID: 7340be19b52f
Revises: b6683f9a105f
Create Date: 2026-10-04 12:08:28.238348

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7340be19b52f"
down_revision: str | Sequence[str] | None = "b6683f9a105f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vehicles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("vin", sa.String(length=17), nullable=False),
        sa.Column("tenant_id", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('provisioning', 'active', 'suspended', 'decommissioned')",
            name="ck_vehicles_status_valid",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vehicles")),
        sa.UniqueConstraint("vin", name=op.f("uq_vehicles_vin")),
    )
    op.create_index("ix_vehicles_tenant_status", "vehicles", ["tenant_id", "status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_vehicles_tenant_status", table_name="vehicles")
    op.drop_table("vehicles")
    # ### end Alembic commands ###
