"""add remote commands

Revision ID: a52bcd546e2d
Revises: 7340be19b52f
Create Date: 2026-10-04 13:26:32.190714

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a52bcd546e2d"
down_revision: str | Sequence[str] | None = "7340be19b52f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "remote_commands",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("vehicle_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=255), nullable=False),
        sa.Column("command_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "command_type IN ('lock', 'unlock', 'start', 'stop', 'honk', 'flash_lights')",
            name="ck_remote_commands_command_type_valid",
        ),
        sa.CheckConstraint(
            "status IN ("
            "'requested', 'queued', 'dispatching', 'sent', "
            "'acknowledged', 'succeeded', 'failed', 'timed_out', "
            "'expired', 'cancelled'"
            ")",
            name="ck_remote_commands_status_valid",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
            name=op.f("fk_remote_commands_vehicle_id_vehicles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_remote_commands")),
        sa.UniqueConstraint(
            "tenant_id",
            "vehicle_id",
            "idempotency_key",
            name="uq_remote_commands_tenant_vehicle_idempotency",
        ),
    )
    op.create_index(
        "ix_remote_commands_status_expires",
        "remote_commands",
        ["status", "expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_remote_commands_tenant_vehicle_created",
        "remote_commands",
        ["tenant_id", "vehicle_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_remote_commands_tenant_vehicle_created", table_name="remote_commands")
    op.drop_index("ix_remote_commands_status_expires", table_name="remote_commands")
    op.drop_table("remote_commands")
    # ### end Alembic commands ###
