"""add outbox failure state

Revision ID: b6683f9a105f
Revises: b1df2faaad51
Create Date: 2026-10-03 21:22:35.267058

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b6683f9a105f"
down_revision: str | Sequence[str] | None = "b1df2faaad51"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "outbox_events", sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("outbox_events", sa.Column("failure_code", sa.String(length=128), nullable=True))
    op.add_column("outbox_events", sa.Column("failure_reason", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("outbox_events", "failure_reason")
    op.drop_column("outbox_events", "failure_code")
    op.drop_column("outbox_events", "failed_at")
    # ### end Alembic commands ###
